### ISSUE TITLE
Error: Count should be greater or equals 2

### ISSUE THREAD

**Issue by creatxrgithub** [DrA1ex/text-graph.js#1]
```
const fn = (x) => {
	return x;
};

let testData = [500, 1200, -900];
for(let i=0, count=0; i<testData.length; i++) {
	//count += testData[i] / 10;  //success
	count += testData[i];  //Error: Count should be greater or equals 2
	chart.addSeriesEntry(0, 0, fn(count));
}
```

**Comment by DrA1ex** [comment]
Hi!

Thank you for getting in touch.

With regard to the reported error "`Error: Count should be greater than or equal to 2`" while using the `addSeriesEntry` method, it seems there might be confusion around the method signature usage. The `addSeriesEntry` method has different signatures for `Plot` (single plot chart) and `MultiPlotChart` (multiple plot chart).

The issue appears to stem from the incorrect usage of the method. The `Plot` version takes only 2 arguments, while the `MultiPlotChart` version takes 3. It seems that in the provided code, the method is being used as if it's the Plot version, while the code suggests it might actually correspond to the `MultiPlotChart` version.

To resolve this, please ensure the correct method signature is used based on the desired chart type. When using `Plot`, call the `addSeriesEntry` method with 2 arguments: `addSeriesEntry(0, fn(count))`. If a `MultiPlotChart` is intended, use the appropriate 3-argument version accordingly.

I'd recommend taking a look at the following examples for clarification:

Example for Plot: [Link](https://codepen.io/DrA1ex/pen/LYaeYwB?editors=0010)
Example for MultiPlotChart: [Link](https://codepen.io/DrA1ex/pen/RwdxwOv?editors=0010)

Please give this a try and let me know if you encounter any further issues. If the problem persists, feel free to reopen the issue or create a new one with additional details.

Best regards.

**Comment by creatxrgithub** [comment]
that's using MultiPlotChart.

**Comment by DrA1ex** [comment]
I previously provided examples to illustrate the functionality of `addSeriesEntry`, assuming the issue might have been a misunderstanding around its signature.

However, since you've confirmed that the signature of the function is not the issue here, I'd like to  ask you to revisit the examples I provided in the previous message. If problems persist, please provide a detailed description of the issues you're facing.
